#!/bin/bash
while [[ -z "$WEBURL" ]]
do
    read -p "Redirect TO this website URL (FQDN): " WEBURL
done
while [[ -z "$WEBNAME" ]]
do
    read -p "Redirect FROM this website URL (FQDN):" WEBNAME
done
cp redirect /etc/nginx/sites-available/$WEBNAME
ln -s /etc/nginx/sites-available/$WEBNAME /etc/nginx/sites-enabled/$WEBNAME
sed -i 's/www.example.com/'$WEBNAME'/g' /etc/nginx/sites-enabled/$WEBNAME
sed -i 's/example.com/'$WEBURL'/g' /etc/nginx/sites-enabled/$WEBNAME
service php7.0-fpm restart
service nginx restart
certbot --nginx -d $WEBNAME
