#!/bin/bash
# This script creates a new MongoDB database and database user
echo A MongoDB Database Creation Script
# Grab new database name, user, and password
read -p "New database name: " NEWDB
read -p "New database user: " NEWUSER
read -p "New database user password: " NEWPWD
# Create database and then user
mongo <<EOF
use $NEWDB
db.createUser( { user: $NEWUSER,
                 pwd: $NEWPWD,
                 roles: [ { role: "readWrite", db: $NEWDB } ]
             } )
exit
EOF