#!/bin/bash
# This script creates a new MySQL database and database user
echo A MySQL Database Creation Script
# Grab new database name, user, and password
read -p "New database name: " NEWDB
read -p "New database user: " NEWUSER
read -p "New database user password: " NEWPWD
# Create new database and user
mysql -uroot -pPasswordHere <<EOF 
CREATE DATABASE $NEWDB;
CREATE USER $NEWUSER@localhost IDENTIFIED BY "$NEWPWD";
GRANT ALL PRIVILEGES ON $NEWDB.* TO $NEWUSER@localhost IDENTIFIED BY '$NEWPWD';
FLUSH PRIVILEGES;
exit
EOF
