#!/bin/bash
# This script creates a wordpress site that is tied to a url, rather than listening on a port.
echo "A Wordpress website creation script"
# Grab variables
while [[ -z "$WEBNAME" ]]
do
    read -p "Website Name: " WEBNAME
done
while [[ -z "$WEBURL" ]]
do
    read -p "Website Url (FQDN): " WEBURL
done
while [[ -z "$PORT" ]]
do
    read -p "PHP-FPM Port: " PORT
done
while [[ -z "$DBNAME" ]]
do
    read -p "Database Name: " DBNAME
done
while [[ -z "$DBUSER" ]]
do
    read -p "Database User: " DBUSER
done
while [[ -z "$DBPWD" ]]
do
    read -s -p "Database Password: " DBPWD
done
while [[ -z "$ROOTPWD" ]]
do
    read -s -p "MySQL Root Password: " ROOTPWD
done
# Create database
echo "Creating database..."
mysql -uroot -p$ROOTPWD <<EOF
CREATE DATABASE $DBNAME;
CREATE USER $DBUSER@localhost IDENTIFIED BY "$DBPWD";
GRANT ALL PRIVILEGES ON $DBNAME.* TO $DBUSER@localhost IDENTIFIED BY "$DBPWD";
FLUSH PRIVILEGES;
exit
EOF
# Create nginx config
echo "Creating nginx config..."
# Copy contents of default file into new config file
cat ~/wpdns >> /etc/nginx/sites-available/$WEBNAME
# Link nginx config to sites-enabled folder
ln -s /etc/nginx/sites-available/$WEBNAME /etc/nginx/sites-enabled/$WEBNAME
# Replace placeholder values from default file with values from read commands
echo "Replacing values..."
sed -i 's/www.domain.ext/'$WEBURL'/g' /etc/nginx/sites-enabled/$WEBNAME
sed -i 's/900x/'$PORT'/g' /etc/nginx/sites-enabled/$WEBNAME
sed -i 's/site_files_here/'$WEBNAME'/g' /etc/nginx/sites-enabled/$WEBNAME
echo "Downloading wordpress files..."
cd /tmp
wget http://wordpress.org/latest.tar.gz
echo "Extracting wordpress files..."
tar xfvx latest.tar.gz
rm -f latest.tar.gz
echo "Moving wordpress files..."
# Copy files
mv /tmp/wordpress /usr/share/nginx/$WEBNAME
echo "Creating php.ini"
touch /usr/share/nginx/$WEBNAME/php.ini
echo "upload_max_filesize = 200M" >> /usr/share/nginx/$WEBNAME/php.ini
echo "post_max_size = 200M" >> /usr/share/nginx/$WEBNAME/php.ini
echo "max_execution_time = 300" >> /usr/share/nginx/$WEBNAME/php.ini
# Change ownership of files to www-data 
echo "Changing ownership of files to www-data..."
chown www-data:www-data /usr/share/nginx/$WEBNAME -R
# Replace placeholder values with database information
echo "Replacing wp-config.php values..."
sed -i 's/database_name_here/'$DBNAME'/g' /usr/share/nginx/$WEBNAME/wp-config.php
sed -i 's/username_here/'$DBUSER'/g' /usr/share/nginx/$WEBNAME/wp-config.php
sed -i 's/password_here/'$DBPWD'/g' /usr/share/nginx/$WEBNAME/wp-config.php
echo "Creating php-fpm pool config..."
# Create php-fpm config
cat ~/default.conf >> /etc/php/7.0/fpm/pool.d/$WEBNAME.conf
# Replace placeholder values with values from read commands
echo "Replacing values..."
sed -i 's/pool_name_here/'$WEBNAME'/g' /etc/php/7.0/fpm/pool.d/$WEBNAME.conf
sed -i 's/900x/'$PORT'/g' /etc/php/7.0/fpm/pool.d/$WEBNAME.conf
# Restart nginx and php-fpm
echo "Restarting services..."
service php7.0-fpm restart
service nginx restart
# Run certbot
echo "Running cerbot..."
certbot --nginx -d www.$WEBURL
echo "All done! =D"