#!/bin/bash
echo "An Nginx redirect config file generator"
# Grab variables
while [[ -z "$APPNAME" ]]
do
  read -p "App Name: " APPNAME
done
while [[ -z "$TODOMAIN" ]]
do
  read -p "Domain to redirect to (i.e. website.com):" TODOMAIN
done
while [[ -z "$FROMDOMAIN" ]]
do
  read -p "Domain to redirect from (i.e. www.website.com):" FROMDOMAIN
done
# Start creating config file
echo "Creating nginx config..."
# Copy contents of default file into new config file
cp reverseproxy /etc/nginx/sites-available/$APPNAME
# Link nginx config to sites-enabled folder
ln -s /etc/nginx/sites-available/$APPNAME /etc/nginx/sites-enabled/$APPNAME
# Replace placeholder values from default file with values from read commands
echo "Replacing values..."
sed -i 's/redirect_from_me/'$FROMDOMAIN'/g' /etc/nginx/sites-available/$APPNAME
sed -i 's/redirect_to_me/'$TODOMAIN'/g' /etc/nginx/sites-available/$APPNAME
# Restart nginx
echo "Restarting nginx..."
systemctl restart nginx
# Run certbot to generate CA certified ssl certificate
echo "Running certbot..."
certbot --nginx -d $FROMDOMAIN
# Finished
echo "All done! =D"