#!/bin/bash
# This script iterates over every folder in a root folder and starts a PM2 process for each app.
# I use it on my demo server, to periodically start all my demo apps in case somebody broke any demos
# Set the folder path below to wherever you keep your PM2 apps
cd ~/apps
for d in */ ; do
    cd "$d"
    dir=${d%?}
    pm2 start server.js --name "$dir"
    cd ..
done