#!/bin/bash

if curl -I --user jacfearsome:117browneyes http://dash1.theselftaughttechie.com | grep -q "200"; then
        echo dash1.theselftaughttechie.com is up!
else
        echo dash1.theselftaughttechie.com is down. Sending email...
        mail -s "dash1.theselftaughttechie.com" "jac.fearsome@gmail.com" <<EOF
dash1.theselftaughttechie.com is down
EOF
fi

if curl -I --user jacfearsome:117browneyes http://dash2.theselftaughttechie.com | grep -q "200"; then
        echo dash2.theselftaughttechie.com is up!
else
        echo dash2.theselftaughttechie.com is down. Sending email...
        mail -s "dash2.theselftaughttechie.com" "jac.fearsome@gmail.com" <<EOF
dash2.theselftaughttechie.com is down
EOF
fi

if curl -I --user jacfearsome:117browneyes http://admin.theselftaughttechie.com/view/dashboard | grep -q "200"; then
        echo admin.theselftaughttechie.com is up!
else
        echo admin.theselftaughttechie.com is down. Sending email...
        mail -s "admin.theselftaughttechie.com" "jac.fearsome@gmail.com" <<EOF
admin.theselftaughttechie.com is down
EOF
fi

if curl -I --user jacfearsome:117browneyes http://domain.theselftaughttechie.com | grep -q "200"; then
        echo domain.theselftaughttechie.com is up!
else
        echo domain.theselftaughttechie.com is down. Sending email...
        mail -s "domain.theselftaughttechie.com" "jac.fearsome@gmail.com" <<EOF
domain.theselftaughttechie.com is down
EOF
fi

if curl -I --user jacfearsome:117browneyes http://lib.theselftaughttechie.com | grep -q "200"; then
        echo lib.theselftaughttechie.com is up!
else
        echo lib.theselftaughttechie.com is down. Sending email...
        mail -s "lib.theselftaughttechie.com" "jac.fearsome@gmail.com" <<EOF
lib.theselftaughttechie.com is down
EOF
fi

if curl -I --user jacfearsome:117browneyes http://paste.theselftaughttechie.com | grep -q "200"; then
        echo paste.theselftaughttechie.com is up!
else
        echo paste.theselftaughttechie.com is down. Sending email...
        mail -s "paste.theselftaughttechie.com" "jac.fearsome@gmail.com" <<EOF
paste.theselftaughttechie.com is down
EOF
fi

if curl -I --user jacfearsome:117browneyes http://stats.theselftaughttechie.com | grep -q "200"; then
        echo stats.theselftaughttechie.com is up!
else
        echo stats.theselftaughttechie.com is down. Sending email...
        mail -s "stats.theselftaughttechie.com" "jac.fearsome@gmail.com" <<EOF
stats.theselftaughttechie.com is down
EOF
fi

if curl -I http://sysadmintools.io | grep -q "200"; then
        echo sysadmintools.io is up!
else
        echo sysadmintools.io is down. Sending email...
        mail -s "sysadmintools.io" "jac.fearsome@gmail.com" <<EOF
sysadmintools.io is down
EOF
fi

if curl -I http://www.devopstools.io/ | grep -q "200"; then
        echo devopstools.io is up!
else
        echo devopstools.io is down. Sending email...
        mail -s "devopstools.io" "jac.fearsome@gmail.com" <<EOF
devopstools.io is down
EOF
fi

