#!/bin/bash
case "$1" in
    devopstools.io)
        read -p "Subdomain to create: " sub
        while [$sub = ""]
        do
            read -p "Subdomain to create: " sub
        done
        echo "$sub IN A 104.247.78.71" >> /var/named/devopstools.io.db
        systemctl restart named
        ;;
    devops-tools.net)
        read -p "Subdomain to create: " sub
        while [$sub = ""]
        do
            read -p "Subdomain to create: " sub
        done
        echo "$sub IN A 104.247.78.71" >> /var/named/devops-tools.net.db
        systemctl restart named
        ;;
    sysadmintools.io)
        read -p "Subdomain to create: " sub
        while [$sub = ""]
        do
            read -p "Subdomain to create: " sub
        done
        echo "$sub IN A 104.247.78.71" >> /var/named/sysadmintools.io.db
        systemctl restart named
        ;;
    sysadmintools.net)
        read -p "Subdomain to create: " sub
        while [$sub = ""]
        do
            read -p "Subdomain to create: " sub
        done
        echo "$sub IN A 104.247.78.71" >> /var/named/sysadmintools.net.db
        systemctl restart named
        ;;
    theselftaughttechie.com)
        read -p "Subdomain to create: " sub
        while [$sub = ""]
        do
            read -p "Subdomain to create: " sub
        done
        echo "$sub IN A 104.247.78.71" >> /var/named/theselftaughttechie.com.db
        systemctl restart named
        ;;
    *)
        echo $"Usage: $0 {devopstools.io|devops-tools.net|sysadmintools.io|sysadmintools.net|theselftaughttechie.com}"
        exit 1
esac