#!/bin/bash
echo "A systemd service creator"
read -p "App Name / Description (nospaces): " APPNAME
read -p "Startup command: " COMMAND
echo $COMMAND >> /home/jac/scripts/startup/$APPNAME.sh
chmod 755 /home/jac/scripts/startup/$APPNAME.sh
echo '[Unit]' >> /etc/systemd/system/$APPNAME.service
echo "Description=$APPNAME" >> /etc/systemd/system/$APPNAME.service
echo '[Service]' >> /etc/systemd/system/$APPNAME.service
echo "ExecStart=/home/jac/scripts/startup/$APPNAME.sh" >> /etc/systemd/system/$APPNAME.service
echo '[Install]' >> /etc/systemd/system/$APPNAME.service
echo 'WantedBy=multi-user.target' >> /etc/systemd/system/$APPNAME.service
systemctl enable $APPNAME
systemctl start $APPNAME
systemctl status $APPNAME
echo "All done!"