#!/bin/bash
echo "An Nginx php-fpm config file generator"
# Grab variables
read -p "App Name: " APPNAME
read -p "Domain (i.e. sub.website.com):" DOMAIN
read -p "PHP-FPM Port: " PORT
read -p "Path to website files: " ROOTPATH
# Start creating config file
echo "Creating nginx config..."
# Copy contents of default file into new config file
cp phpconfig /etc/nginx/sites-available/$APPNAME
# Link nginx config to sites-enabled folder
ln -s /etc/nginx/sites-available/$APPNAME /etc/nginx/sites-enabled/$APPNAME
# Replace placeholder values from default file with values from read commands
echo "Replacing values..."
sed -i 's/sub.domain.ext/'$DOMAIN'/g' /etc/nginx/sites-available/$APPNAME
sed -i 's/900x/'$PORT'/g' /etc/nginx/sites-available/$APPNAME
sed -i 's/appname/'$APPNAME'/g' /etc/nginx/sites-available/$APPNAME
sed -i 's/root_path_here/"$ROOTPATH"/g' /etc/nginx/sites-available/$APPNAME
# Create php-fpm pool
echo "Creating PHP-FPM config..."
cp default.conf /etc/php/7.0/fpm/pool.d/$APPNAME.conf
echo "Replacing values..."
sed -i 's/pool_name_here/'$APPNAME'/g' /etc/php/7.0/fpm/pool.d/$APPNAME.conf
sed -i 's/900x/'$PORT'/g' /etc/php/7.0/fpm/pool.d/$APPNAME.conf
# Restart services
echo "Restarting services..."
service php7.0-fpm restart
service nginx restart
# Run certbot to generate CA certified ssl certificate
echo "Running certbot..."
certbot --nginx -d $DOMAIN
# Finished
echo "All done! =D"