#!/bin/bash
# Designed with Ubuntu
# git-pull - A script that iterates over every folder in a root folder and runs git pull in each folder

if [ -z "$1" ]
then
    echo "FATAL: Please enter the root directory path"
    echo "Example: sudo bash git-pull /path/to/root"
else
    ROOT=$1
    cd $ROOT
    for d in */ ; do
        cd "$d"
        git pull
        cd ..
    done
fi